# Generated by Django 3.2.9 on 2021-12-01 08:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Care_taker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number')),
            ],
        ),
    ]
