# Generated by Django 2.2.16 on 2021-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care_taker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
