# Generated by Django 3.2.9 on 2021-12-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0002_auto_20211202_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care_taker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
