# Generated by Django 3.2.9 on 2021-12-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0004_auto_20211205_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autisticchildren',
            name='AWT_device_id',
        ),
        migrations.RemoveField(
            model_name='autisticchildren',
            name='caretaker_id',
        ),
        migrations.AddField(
            model_name='autisticchildren',
            name='AWT_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='caretaker.awt_device'),
        ),
        migrations.AddField(
            model_name='autisticchildren',
            name='caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker', to='caretaker.care_taker'),
        ),
        migrations.AddField(
            model_name='care_taker',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='caretaker.autisticchildren'),
        ),
    ]
