# Generated by Django 3.2.9 on 2021-12-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caretaker', '0005_auto_20211205_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='care_taker',
            name='home_address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='care_taker',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
