# Generated by Django 3.2.9 on 2021-12-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0006_auto_20211208_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care_taker',
            name='caretaker_name',
        ),
    ]
