# Generated by Django 3.2.9 on 2021-12-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0007_remove_care_taker_caretaker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care_taker',
            name='child',
        ),
    ]
