# Generated by Django 3.2.9 on 2021-12-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0008_remove_care_taker_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autisticchildren',
            name='AWT_device',
        ),
        migrations.AddField(
            model_name='autisticchildren',
            name='AWT_device_serialNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AWT_Device',
        ),
    ]
